# 

version: 0.2

# This primary buildspec is used by the CodePipeline project created MANUALLY
# Its sole purpose is to define the stages and artifacts passed between them.
phases:
  install:
    commands:
      - echo "Starting the Self-Healing Pipeline Orchestration..."

artifacts:
  files:
    - "**/*"