apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
  namespace: default
  annotations:
    # This annotation is CRITICAL for CloudWatch to get metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  selector:
    app: simple-bank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # This creates an AWS ELB (Classic Load Balancer)
